name: Pack and publish DEV-Builds
on:
  workflow_dispatch
#  push:
#    branches: [dev/1.12.2]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare Package-Name
    runs-on: self-hosted
    outputs:
      font-name: ${{ steps.properties.outputs.font-name }}
      ores-name: ${{ steps.properties.outputs.ores-name }}
    steps:
      - id: checkout-repo
        name: Checkout
        uses: actions/checkout@v3.0.2

      - id: properties
        name: Export Modpack Version
        run: |
          MC_VERSION="$(echo ${{ github.ref_name }} | cut -d '/' -f2)"
          BUILD_ENV="$(echo ${{ github.ref_name }} | cut -d '/' -f1)"
          FONT_VERSION="$(cat ./fontfiles/VERSION)"
          ORES_VERSION="$(cat ./oresources/VERSION)"
          
          if [ BUID_ENV == "dev" ]; then
            FONT_VERSION="$(echo $FONT_VERSION-DEV-${{ github.build_num }})"
            ORES_VERSION="$(echo $ORES_VERSION-DEV-${{ github.build_num }})"
          fi
          
          echo "::set-output name=font-name::ampilution-fonts-$MC_VERSION-$FONT_VERSION"
          echo "::set-output name=ores-name::ampilution-oresources-$MC_VERSION-$ORES_VERSION"


  pack-fonts:
    name: pack-fonts
    runs-on: self-hosted
    needs: prepare
    steps:
      - name: Checkout Oresources
        uses: actions/checkout@v3.0.2

      - name: Move files
        run: |
          mkdir ./zip
          mv ./fontfiles ./zip/

      - name: Collect ZIP
        uses: actions/upload-artifact@v3
        with:
          name: ${{ needs.prepare.outputs.font-name }}
          path: |
            ./zip/
            !./zip/fontfiles/VERSION

  pack-ores:
    name: pack-oresources
    runs-on: self-hosted
    needs: prepare
    steps:
      - name: Checkout Oresources
        uses: actions/checkout@v3.0.2

      - name: Move files
        run: |
          mkdir ./zip
          mv ./oresources ./zip/

      - name: Collect ZIP
        uses: actions/upload-artifact@v3
        with:
          name: ${{ needs.prepare.outputs.ores-name }}
          path: |
            ./zip/
            !./zip/oresources/VERSION
            !./zip/oresources/.gitignore


